title:              Ji's Blog
email:              jisung4943@gmail.com
description:        일기장 낙서장
author:             Sunghwan Ji
baseurl:            ""
url:                "https://sunghwanji.github.io"

# Social Profiles
twitter_username:   
github_username:    sunghwanji
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
